### ISSUE TITLE
Redis keys not expiring

### ISSUE THREAD

**Issue by cdaguerre** [darkweak/souin#417]
The Redis storage provider does not set key TTL correctly (using Redis 6.2). Or is the behavior below expected?
<img width="776" alt="Capture d’écran 2023-12-13 à 14 00 38" src="https://github.com/darkweak/souin/assets/4642448/5aa92f2f-ad3b-4f6b-8c27-fdfb8344a716">

**Comment by darkweak** [comment]
Hey @cdaguerre thats definitively a bug 😄

**Comment by darkweak** [comment]
@cdaguerre can you paste an the request you're sending and the responses (the one with the store and the one with the age/ttl) ?

**Comment by darkweak** [comment]
@cdaguerre should be fixed in the latest release.

**Comment by K0tBegemot** [comment]
I have this problem too. In standlone mode with latest release, /flush method does not clear the cache contents

**Comment by darkweak** [comment]
@K0tBegemot do you have a curl request?

**Comment by HobMartin** [comment]
Same problem to me. I use Redis cluster and when I send `PURGE` request, keys in Redis still exist.
After trying to reproduce it, I believe I understand why it happened.

Keys and Stale was store in one cluster slot, but IDXs stores in different and when `PURGE` request call `DeleteMany` method I've got `panic: multi key command with different key slots are not allowed`.

How fix that?

**Comment by HobMartin** [comment]
@darkweak Of course. 
My Caddy config:
```Caddyfile
(redis_cache) {
  redis {
    configuration {
      InitAddress clustercfg.xxxxx.yyyyy.use1.cache.amazonaws.com:6379 // here cluster config endpoint
      TLSConfig
      Username "username"
      Password "password"
    }
  }
}
{
  cache {

    api {
      basepath /_cache
      souin
    }
    import redis_cache

    stale 60s
    ttl 120s

    key {
      disable_body
      disable_method
      headers Content-Type Authorization
      hide
    }
  }
}
```
And curl request
```bash
curl -x PURGE https://cache-testing.test.com/_cache/souin/cache-testing
```

I use Souin Api endpoint with name of site to remove caching for a specific site. BTW, 
```bash
curl -x PURGE https://cache-testing.test.com/_cache/souin/
```
doesn't work too.
And PURGE by surrogate key, didn't clear as well

FYI, I specify TLSConfig, because without it Caddy failed when starting.

**Comment by HobMartin** [comment]
@darkweak any updates?

**Comment by darkweak** [comment]
@HobMartin sorry for the delay. I opened a PR that concerns the redis storage https://github.com/darkweak/souin/pull/489. I will try to take your issue in it. About the hashtags, it it really mandatory? Maybe this https://github.com/redis/rueidis/discussions/177#discussioncomment-5136914 could solve that instead (`DoMulti` usage).

**Comment by darkweak** [comment]
@HobMartin I pushed a new commit that may support the redis hashtags. You can enable it using the HashTag directive in the redis configuration.
```
{
    order cache before rewrite
    cache {
        api {
            souin
        }
        ttl 1000s
    }
}

:4443
respond "Hello World!"

route /redis-configuration/* {
    cache {
        redis {
            configuration {
                HashTag "{something}"
                ClientName souin-redis
                InitAddress 127.0.0.1:6379
                SelectDB 0
            }
        }
    }
    respond "Hello redis"
}
```

By the way I fixed the purge but the API is the following to flush all keys:
```
curl -X PURGE '{YOUR_DOMAIN}/{SOUIN_API_PATH}/flush'
```

You can try that using the latest commit `a9f87ce02be5b871101db189345eb3c81ce01676`:
```
xcaddy build  --with github.com/darkweak/souin/plugins/caddy@a9f87ce02be5b871101db189345eb3c81ce01676  --with github.com/darkweak/souin@a9f87ce02be5b871101db189345eb3c81ce01676
```

**Comment by HobMartin** [comment]
@darkweak what about of support [caddy placeholders](https://caddyserver.com/docs/caddyfile/concepts#placeholders) in hashtag name? This will be so helpful in my case.

**Comment by darkweak** [comment]
@HobMartin placeholders support is currently in progress here https://github.com/darkweak/souin/pull/514 🙂

**Comment by HobMartin** [comment]
@darkweak thanks for adding placeholders. There is awesome feature!

But I'm still having a problem with deleting keys by regex. Flush request works well, but regex didn't 😓

Also, I was seen in source code, and see that bulk delete using delete method from storage, how this method will delete keys by regex, maybe it should be DeleteMany that use scan command from Redis?
